# Generated by Django 5.1 on 2024-09-24 02:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEPP',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('reportado', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
