# Generated by Django 5.1 on 2024-09-24 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPP', '0002_estadoepp'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoepp',
            name='PersonalEpps',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EPP.personalepps'),
            preserve_default=False,
        ),
    ]
