# Generated by Django 5.1 on 2024-10-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPP', '0003_estadoepp_personalepps'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoepp',
            name='estado',
            field=models.CharField(default='bueno', max_length=100),
        ),
    ]
