# Generated by Django 5.1 on 2024-10-08 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emergencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incendios',
            name='jefe_servicio',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ambulancia',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulancia', to='Emergencias.servicio'),
        ),
        migrations.AlterField(
            model_name='incendios',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incendios', to='Emergencias.servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='servicio',
            field=models.CharField(choices=[('1', 'Varios'), ('2', 'Ambulancia'), ('3', 'Incendios')], max_length=50),
        ),
        migrations.AlterField(
            model_name='varios',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varios', to='Emergencias.servicio'),
        ),
    ]
