# Generated by Django 5.1 on 2024-10-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emergencias', '0002_incendios_jefe_servicio_alter_ambulancia_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
