# Generated by Django 5.1 on 2024-10-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('kmEntrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kmSalida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jefeServicio', models.CharField(max_length=100)),
                ('bomberoReporta', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('salida_hora', models.DateTimeField()),
                ('entrada_hora', models.DateTimeField()),
                ('servicio', models.CharField(choices=[('Varios', 'Varios'), ('Ambulancia', 'Ambulancia'), ('Incendios', 'Incendios')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('turno', models.CharField(max_length=50)),
                ('telefonista', models.CharField(max_length=100)),
                ('tipo_servicio_varios', models.CharField(blank=True, max_length=100, null=True)),
                ('autorizado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_traslado', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_paciente', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_paciente', models.CharField(blank=True, max_length=255, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('traslado_A', models.CharField(blank=True, max_length=100, null=True)),
                ('forma_aviso', models.CharField(blank=True, max_length=100, null=True)),
                ('servicio_incendio_inmueble', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('perdida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proporcion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('clase_fuego', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_efectiva', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
