# Generated by Django 5.1 on 2024-10-03 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicio',
            new_name='ServicioPrincipal',
        ),
    ]
