# Generated by Django 5.1 on 2024-10-02 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='autorizado_por',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='clase_fuego',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='direccion_paciente',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='direccion_traslado',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='forma_aviso',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='hora_efectiva',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='nombre_paciente',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='perdida',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='proporcion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='servicio_incendio_inmueble',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='tipo_servicio_varios',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='traslado_A',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='valor',
        ),
        migrations.CreateModel(
            name='Ambulancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_traslado', models.CharField(max_length=255)),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('direccion_paciente', models.CharField(max_length=255)),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('traslado_A', models.CharField(max_length=100)),
                ('forma_aviso', models.CharField(max_length=100)),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ambulancia', to='Servicios.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Incendios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio_incendio_inmueble', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perdida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proporcion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('clase_fuego', models.CharField(max_length=50)),
                ('hora_efectiva', models.DateTimeField()),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incendios', to='Servicios.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Varios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio_varios', models.CharField(max_length=100)),
                ('autorizado_por', models.CharField(max_length=100)),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='varios', to='Servicios.servicio')),
            ],
        ),
    ]
