# Generated by Django 5.1 on 2024-10-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Herramientas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientoherramienta',
            name='tiempo_mantenimiento',
            field=models.DateTimeField(default='2000-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
