# Generated by Django 5.1 on 2024-10-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Herramientas', '0002_alter_mantenimientoherramienta_tiempo_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientoherramienta',
            name='tiempo_mantenimiento',
            field=models.DateField(),
        ),
    ]
