# Generated by Django 5.1 on 2024-09-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publico', '0002_emergencias_reportado_emergencias_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencias',
            name='atendido',
            field=models.BooleanField(default=False),
        ),
    ]
