# Generated by Django 5.1 on 2024-09-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_brithday_profile_direccion_profile_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='brithday',
            new_name='birthday',
        ),
        migrations.AlterField(
            model_name='profile',
            name='pdi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
