# Generated by Django 5.1 on 2024-08-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('stock_inicial', models.IntegerField(default=0)),
                ('stock_actual', models.IntegerField(default=0)),
            ],
        ),
    ]
