# Generated by Django 5.1 on 2024-08-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrativo', '0003_remove_insumos_cantidadtomada_insumolog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='codigo',
            field=models.AutoField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
