# Generated by Django 5.1 on 2024-08-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrativo', '0004_alter_insumos_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
